name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # rebuild everyday at 7:30
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron:  '30 7 * * *'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(builtins.getFlake (builtins.toString ./.)).inputs.nixpkgs.lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: toyvo
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Check evaluation
      run: nix flake show --option allow-import-from-derivation true
    - name: Build nix packages
      run: nix run nixpkgs#nix-build-uncached -- ci.nix -A cacheOutputs
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=https://github.com/ToyVo/nur-packages"
